"""Slack message formatting utilities."""

from typing import Optional


def format_task_started(dog_name: str, task_description: str) -> str:
    """
    Format a message for when a dog starts a task.

    Args:
        dog_name: Name of the dog taking the task
        task_description: Description of the task

    Returns:
        Formatted Slack message
    """
    return f"🐕 *{dog_name}* is taking this task!\n\n_{task_description}_"


def format_task_completed(pr_url: str, dog_name: str) -> str:
    """
    Format a message for when a task is completed.

    Args:
        pr_url: URL of the created PR
        dog_name: Name of the dog that completed the task

    Returns:
        Formatted Slack message
    """
    return f"✅ *PR ready!*\n\n{pr_url}\n\n_Completed by {dog_name}_"


def format_task_failed(error_message: str, dog_name: str) -> str:
    """
    Format a message for when a task fails.

    Args:
        error_message: Error description
        dog_name: Name of the dog that attempted the task

    Returns:
        Formatted Slack message
    """
    return f"❌ *Task failed*\n\n```{error_message}```\n\n_Attempted by {dog_name}_"


def format_pr_body(task_description: str, files_modified: Optional[list] = None) -> str:
    """
    Format PR body with task details.

    Args:
        task_description: Original task description
        files_modified: List of files that were modified (optional)

    Returns:
        Formatted PR body in markdown
    """
    body = f"""## Task Description
{task_description}

## Changes Made
This PR was automatically generated by Dogwalker's AI coding agent.
"""

    if files_modified:
        body += "\n### Files Modified\n"
        for file in files_modified:
            body += f"- `{file}`\n"

    body += """
## Review Checklist
- [ ] Code follows project style guidelines
- [ ] No unintended side effects
- [ ] Functionality works as expected
- [ ] Tests pass (if applicable)

---
🤖 Generated with Dogwalker AI

Co-Authored-By: Dogwalker <noreply@dogwalker.dev>
"""
    return body
